//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using FullSerializer;

namespace AssemblyCSharp
{
	public class JsonSerializer
	{
		private static fsSerializer _serializer = new fsSerializer();
		
		public static string Serialize(Type type, object value) {
			// serialize the data
			fsData data;
			var fail = _serializer.TrySerialize(type, value, out data);
			if (fail.Failed) throw new Exception(fail.FailureReason);
			
			// emit the data via JSON
			return fsJsonPrinter.CompressedJson(data);
		}
		
		public static object Deserialize(Type type, string serializedState) {
			fsFailure fail;
			
			// step 1: parse the JSON data
			fsData data;
			fail = fsJsonParser.Parse (serializedState, out data);
			if (fail.Failed)
				throw new Exception (fail.FailureReason);
			
			// step 2: deserialize the data
			object deserialized = null;
			fail = _serializer.TryDeserialize (data, type, ref deserialized);
			if (fail.Failed)
				throw new Exception (fail.FailureReason);
			
			return deserialized;
		}
	}
}

