//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Character
	{
		public string name { get; set; }
		public CharacterClass charClass { get; set; }
		public CharacterRace charRace { get; set; }
		public CharacterFaction faction { get; set; }
		public CharacterGender gender { get; set; }

		public Character(string name, CharacterClass charClass, CharacterRace charRace) {
			this.name = name;
			this.charClass = charClass;
			this.charRace = charRace;
		}
	}
}