//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum CharacterClass
	{
		Error = 0, Combatant = 1, Laborer = 2
	}
	public enum CharacterRace
	{
		Error = 0, Human = 1, Dwarf = 2, Elf = 3, IgnezorOrc = 4, TerrazorOrc = 5, BelzorOrc = 6
	}
	public enum CharacterFaction
	{
		Error = 0, TheAccord = 1, IgnezorOrc = 2, TerrazorOrc = 3, BelzorOrc = 4
	}
	public enum CharacterSex
	{
		Error = 0, Male = 1, Female = 2
	}

	public static class EnumFunctions {
		public static CharacterFaction getFactionFromRace(CharacterRace race) {
			if ((race == CharacterRace.Human) || (race == CharacterRace.Dwarf) || (race == CharacterRace.Elf)) {
				return CharacterFaction.TheAccord;
			} else if (race == CharacterRace.IgnezorOrc) {
				return CharacterFaction.IgnezorOrc;
			} else if (race == CharacterRace.TerrazorOrc) {
				return CharacterFaction.TerrazorOrc;
			} else if (race == CharacterRace.BelzorOrc) {
				return CharacterFaction.BelzorOrc;
			} else {
				//figure out how to throw error here
				return CharacterFaction.Error;
			}
		}
	}
}

