//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum CharacterClass
	{
		Combatant = 1, Laborer = 2
	}
	public enum CharacterRace
	{
		Human = 1, Dwarf = 2, Elf = 3, IgnezorOrc = 4, TerrazorOrc = 5, BelzorOrc = 6
	}
	public enum CharacterFaction
	{
		TheAlliance = 1, IgnezorOrc = 2, TerrazorOrc = 3, BelzorOrc = 4
	}
	public enum CharacterGender
	{
		Male = 1, Female = 2
	}
}

