//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Character
	{
		public string charName { get; set; }
		public CharacterClass charClass { get; set; }
		public CharacterRace charRace { get; set; }
		public CharacterFaction charFaction { get; set; }
		public CharacterSex charSex { get; set; }

		public Character() {

		}
	}
}